import { Flowchart, TriageSession, FlowchartSchema } from '../types';

/**
 * Serialize flowchart to JSON string
 */
export function serializeFlowchart(flowchart: Flowchart): string {
    return JSON.stringify(flowchart, null, 2);
}

/**
 * Parse and validate JSON string back to Flowchart
 */
export function deserializeFlowchart(json: string): Flowchart {
    const data = JSON.parse(json);
    // Validate with Zod
    return FlowchartSchema.parse(data);
}

/**
 * Generate a human-readable text summary of a triage session for sharing
 */
export function generateSessionSummary(session: TriageSession): string {
    const date = new Date(session.startedAt).toLocaleString();
    let summary = `🏥 TRIAGE SESSION SUMMARY\n`;
    summary += `--------------------------\n`;
    summary += `Patient ID: ${session.patientId}\n`;
    summary += `Protocol: ${session.flowchartName}\n`;
    summary += `Date: ${date}\n`;
    summary += `Status: ${session.isCompleted ? 'COMPLETED' : 'INCOMPLETE'}\n`;

    if (session.isCompleted) {
        summary += `\n🚨 RESULT: ${session.finalRiskLevel?.toUpperCase() || 'UNKNOWN'}\n`;
        summary += `Risk Score: ${session.finalRiskScore || 0}/100\n`;
        summary += `Priority: ${session.finalPriority?.toUpperCase() || 'UNKNOWN'}\n`;
        summary += `Outcome: ${session.outcome || 'No outcome recorded'}\n`;
    }

    summary += `\n🛤 PATH TAKEN:\n`;
    session.steps.forEach((step, index) => {
        summary += `${index + 1}. ${step.nodeTitle}`;
        if (step.chosenOptionLabel) {
            summary += ` → [${step.chosenOptionLabel}]`;
        }
        summary += `\n`;
    });

    if (session.notes) {
        summary += `\n📝 NOTES:\n${session.notes}\n`;
    }

    summary += `\nGenerated by TriageFlow - 100% Offline Medical DSS\n`;
    return summary;
}

/**
 * Export all sessions as JSON
 */
export function exportAllSessions(sessions: Record<string, TriageSession>): string {
    return JSON.stringify(Object.values(sessions), null, 2);
}
